
_target_: src.policies.epsilon_greedy.GreedyPolicy

Qnet: 
  _target_: src.models.fully_connected.NoisyQNet
  _partial_: true
  hidden_layers: [256,256,256]
  activation: 
    _target_: torch.nn.ELU
    _partial_: true
  log_std_init: -2.0

