# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=optuna experiment=example

defaults:
  - override /hydra/launcher: ray
  - override /hydra/sweeper: optuna

hydra:

  mode: "MULTIRUN"

  launcher:
    ray:
      remote:
        num_cpus: 4
      init:
        local_mode: false

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    n_trials: 20
    n_jobs: 4
    direction: minimize

    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 4

    params:
      agent.tau: interval(0.0001, 0.1)



